"""empty message

Revision ID: 004c42d8522c
Revises: fcf6dea37283
Create Date: 2018-08-25 20:52:27.180318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004c42d8522c'
down_revision = 'fcf6dea37283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_teams', 'team_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint('player_teams_team_name_key', 'player_teams', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('player_teams_team_name_key', 'player_teams', ['team_name'])
    op.alter_column('player_teams', 'team_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
