"""empty message

Revision ID: 02e8336fd603
Revises: 46cb02a694aa
Create Date: 2018-08-26 16:24:37.624491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e8336fd603'
down_revision = '46cb02a694aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    league_type_table = op.create_table('league_types',
    sa.Column('league_type_id', sa.Integer(), nullable=False),
    sa.Column('league_type_name', sa.String(length=30), nullable=True),
    sa.Column('league_type_description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('league_type_id'),
    sa.UniqueConstraint('league_type_name')
    )

    op.bulk_insert(league_type_table, [{'league_type_name': 'STANDARD',
                                  'league_type_description': 'Standard Survivor Pool League'}])
    op.bulk_insert(league_type_table, [{'league_type_name': 'FREE',
                                        'league_type_description': 'Free Survivor Pool League'}])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_types')
    # ### end Alembic commands ###
