"""empty message

Revision ID: 2259890fb9a3
Revises: 02e8336fd603
Create Date: 2018-08-26 16:38:41.428794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2259890fb9a3'
down_revision = '02e8336fd603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('league_type_id', sa.Integer(), server_default='1', nullable=True))
    op.create_foreign_key(None, 'leagues', 'league_types', ['league_type_id'], ['league_type_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.drop_column('leagues', 'league_type_id')
    # ### end Alembic commands ###
