"""empty message

Revision ID: 30dafb6c48b9
Revises: 838523588531
Create Date: 2018-09-25 22:16:49.444978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30dafb6c48b9'
down_revision = '838523588531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'completed')
    # ### end Alembic commands ###
