"""empty message

Revision ID: 354c694b01c2
Revises: 3c4837f7dd21
Create Date: 2018-07-17 22:51:58.394932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354c694b01c2'
down_revision = '3c4837f7dd21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('games', sa.Column('test_column', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('games', 'test_column')
    # ### end Alembic commands ###
