"""Games table

Revision ID: 3c4837f7dd21
Revises: 
Create Date: 2018-07-16 22:31:00.761845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4837f7dd21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('home_team_name', sa.String(length=45), nullable=True),
    sa.Column('home_team_city_abbr', sa.String(length=10), nullable=True),
    sa.Column('home_team_score', sa.Integer(), nullable=True),
    sa.Column('away_team_name', sa.String(length=45), nullable=True),
    sa.Column('away_team_city_abbr', sa.String(length=10), nullable=True),
    sa.Column('away_team_score', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(length=3), nullable=True),
    sa.Column('time', sa.String(length=5), nullable=True),
    sa.Column('game_date', sa.DateTime(), nullable=True),
    sa.Column('quarter', sa.String(length=3), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
