"""empty message

Revision ID: 3eed27ad2180
Revises: c21b83512364
Create Date: 2018-07-30 10:06:39.435046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eed27ad2180'
down_revision = 'c21b83512364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=45), nullable=True),
    sa.Column('team_name', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('has_paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_teams')
    # ### end Alembic commands ###
