"""empty message

Revision ID: 406f56dd6a90
Revises: 03176723e63a
Create Date: 2018-08-28 19:31:24.341412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406f56dd6a90'
down_revision = '03176723e63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_message_types = op.create_table('user_message_types',
    sa.Column('message_type_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('message_type_id')
    )

    op.bulk_insert(user_message_types, [{'message_type': 'DEFAULT'}])


    op.create_table('user_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.String(length=500), nullable=False),
    sa.Column('message_type_id', sa.Integer(), server_default='1', nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('read', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('read_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_type_id'], ['league_types.league_type_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_messages')
    op.drop_table('user_message_types')
    # ### end Alembic commands ###
