"""empty message

Revision ID: 41ddb2695237
Revises: bdeb1a1c0c5f
Create Date: 2018-08-29 19:51:12.700103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ddb2695237'
down_revision = 'bdeb1a1c0c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('start_week', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'start_week')
    # ### end Alembic commands ###
