"""empty message

Revision ID: 46cb02a694aa
Revises: 004c42d8522c
Create Date: 2018-08-26 15:05:14.025492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46cb02a694aa'
down_revision = '004c42d8522c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_teams', sa.Column('streak', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_teams', 'streak')
    # ### end Alembic commands ###
