"""empty message

Revision ID: 6d6fe8155f05
Revises: 5f6f6fae7453
Create Date: 2018-08-24 19:14:54.487356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6fe8155f05'
down_revision = '5f6f6fae7453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_teams',
    sa.Column('nfl_team_id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('city_state', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=70), nullable=False),
    sa.Column('nickname', sa.String(length=40), nullable=False),
    sa.Column('conference', sa.String(length=5), nullable=False),
    sa.Column('division', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('nfl_team_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nfl_teams')
    # ### end Alembic commands ###
