"""empty message

Revision ID: 7c3a42046041
Revises: 3eed27ad2180
Create Date: 2018-07-30 10:54:06.899936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3a42046041'
down_revision = '3eed27ad2180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'player_teams', ['team_name'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'player_teams', type_='unique')
    # ### end Alembic commands ###
