"""empty message

Revision ID: 838523588531
Revises: d2ebab3598f0
Create Date: 2018-09-25 22:14:47.712193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838523588531'
down_revision = 'd2ebab3598f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('completed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
