"""empty message

Revision ID: 86719b64562c
Revises: 41ddb2695237
Create Date: 2018-09-13 21:31:00.468905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86719b64562c'
down_revision = '41ddb2695237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_messages',
    sa.Column('message_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('message_text', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('show_message', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('message_type', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='admin_messages_user_id_fkey'),
    sa.PrimaryKeyConstraint('message_id', name='admin_messages_pkey')
    )
    # ### end Alembic commands ###
