"""empty message

Revision ID: 8b70d921e6b9
Revises: bd8b061e4dc1
Create Date: 2018-08-24 22:56:33.039854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b70d921e6b9'
down_revision = 'bd8b061e4dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadiums',
    sa.Column('stadium_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.Column('stadium_name', sa.String(length=100), nullable=False),
    sa.Column('stadium_state', sa.String(length=5), nullable=False),
    sa.Column('roof_type', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('stadium_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stadiums')
    # ### end Alembic commands ###
