"""empty message

Revision ID: 8b85d870ca28
Revises: 8ebef6ea74ae
Create Date: 2018-08-13 18:39:14.396546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b85d870ca28'
down_revision = '8ebef6ea74ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=45), nullable=True),
    sa.Column('message_text', sa.String(length=500), nullable=False),
    sa.Column('show_message', sa.Boolean(), nullable=True),
    sa.Column('message_type', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_messages')
    # ### end Alembic commands ###
