"""empty message

Revision ID: 9f0e68240f89
Revises: f9c06d50a757
Create Date: 2018-08-06 19:53:33.561949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0e68240f89'
down_revision = 'f9c06d50a757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_teams', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_teams', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
