"""empty message

Revision ID: ae32bcde1057
Revises: f16a20fe666c
Create Date: 2020-09-10 15:56:10.879289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae32bcde1057'
down_revision = 'f16a20fe666c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('has_started', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'has_started')
    op.create_table('zstadiums2019',
    sa.Column('stadium_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('stadium_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('stadium_state', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('roof_type', sa.VARCHAR(length=40), autoincrement=False, nullable=True)
    )
    op.create_table('znfl_teams2019',
    sa.Column('nfl_team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('abbreviation', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('city_state', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=70), autoincrement=False, nullable=True),
    sa.Column('nickname', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('conference', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('division', sa.VARCHAR(length=5), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
