"""empty message

Revision ID: bdeb1a1c0c5f
Revises: d3dcb4b5fb74
Create Date: 2018-08-28 21:59:17.902123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdeb1a1c0c5f'
down_revision = 'd3dcb4b5fb74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_messages_message_type_id_fkey', 'user_messages', type_='foreignkey')
    op.create_foreign_key(None, 'user_messages', 'user_message_types', ['message_type_id'], ['message_type_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_messages', type_='foreignkey')
    op.create_foreign_key('user_messages_message_type_id_fkey', 'user_messages', 'league_types', ['message_type_id'], ['league_type_id'])
    # ### end Alembic commands ###
