"""empty message

Revision ID: c21b83512364
Revises: 354c694b01c2
Create Date: 2018-07-29 14:34:41.993345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21b83512364'
down_revision = '354c694b01c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=45), nullable=False),
    sa.Column('full_name', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('picture_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_column('games', 'test_column')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('test_column', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('users')
    # ### end Alembic commands ###
