"""empty message

Revision ID: d2ebab3598f0
Revises: ffb88672ec14
Create Date: 2018-09-25 22:05:30.778098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ebab3598f0'
down_revision = 'ffb88672ec14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('leagues_won', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'leagues_won')
    # ### end Alembic commands ###
