"""empty message

Revision ID: d3dcb4b5fb74
Revises: 406f56dd6a90
Create Date: 2018-08-28 19:37:41.068077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3dcb4b5fb74'
down_revision = '406f56dd6a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_messages', sa.Column('user_id', sa.String(length=45), nullable=True))
    op.create_foreign_key(None, 'user_messages', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_messages', type_='foreignkey')
    op.drop_column('user_messages', 'user_id')
    # ### end Alembic commands ###
