"""empty message

Revision ID: d4e6e6faacfb
Revises: 30dafb6c48b9
Create Date: 2018-10-10 11:01:36.616646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e6e6faacfb'
down_revision = '30dafb6c48b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stadiums', 'stadium_state',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stadiums', 'stadium_state',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    # ### end Alembic commands ###
