"""empty message

Revision ID: de8f05fc7f7b
Revises: 9f0e68240f89
Create Date: 2018-08-06 21:38:53.253252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8f05fc7f7b'
down_revision = '9f0e68240f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pick_model',
    sa.Column('pick_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('week_num', sa.Integer(), nullable=False),
    sa.Column('nfl_team_name', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['player_teams.team_id'], ),
    sa.PrimaryKeyConstraint('pick_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pick_model')
    # ### end Alembic commands ###
