"""empty message

Revision ID: f9c06d50a757
Revises: 7c3a42046041
Create Date: 2018-07-30 23:43:01.814146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c06d50a757'
down_revision = '7c3a42046041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('league_name', sa.String(length=50), nullable=False),
    sa.Column('league_description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.add_column('player_teams', sa.Column('league_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'player_teams', 'leagues', ['league_id'], ['league_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player_teams', type_='foreignkey')
    op.drop_column('player_teams', 'league_id')
    op.drop_table('leagues')
    # ### end Alembic commands ###
