"""empty message

Revision ID: ffb88672ec14
Revises: 86719b64562c
Create Date: 2018-09-25 21:48:42.686540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb88672ec14'
down_revision = '86719b64562c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('completed', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'completed')
    # ### end Alembic commands ###
